# Generated by Django 4.2.16 on 2024-10-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaycTransferEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_id", models.IntegerField()),
                ("from_address", models.CharField(max_length=128, null=True)),
                ("to_address", models.CharField(max_length=128, null=True)),
                (
                    "transaction_hash",
                    models.CharField(
                        db_index=True, max_length=128, null=True, unique=True
                    ),
                ),
                ("block_number", models.IntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
